import {
  noiseCityTrafic,
  noiseRainCity,
  noiseFireplace,
  noiseCampfire,
  noiseForestNight,
  noiseRainForest,
  noiseWaves,
  noiseFan,
  noiseSummerStorm,
  noiseRiver,
  noiseBirds,
  noisePeopleTalk,
  noiseWind,
  noiseOcean,
  noiseSnow,
  noiseKeyboard,
} from '../../assets/audios/noises';

export const NOISE_LINKS = [
  noiseCityTrafic,
  noiseRainCity,
  noiseFireplace,
  noiseCampfire,
  noiseForestNight,
  noiseRainForest,
  noiseWaves,
  noiseFan,
  noiseSummerStorm,
  noiseRiver,
  noiseBirds,
  noisePeopleTalk,
  noiseWind,
  noiseOcean,
  noiseSnow,
  noiseKeyboard,
];
