import {
  sleepy10Audio,
  sleepy11Audio,
  sleepy12Audio,
  sleepy13Audio,
  sleepy14Audio,
  sleepy15Audio,
  sleepy16Audio,
  sleepy17Audio,
  sleepy1Audio,
  sleepy2Audio,
  sleepy3Audio,
  sleepy4Audio,
  sleepy5Audio,
  sleepy6Audio,
  sleepy7Audio,
  sleepy8Audio,
  sleepy9Audio,
} from '../../assets/audios/sleepy';

const SLEEPY_LINKS = [
  sleepy1Audio,
  sleepy2Audio,
  sleepy3Audio,
  sleepy4Audio,
  sleepy5Audio,
  sleepy6Audio,
  sleepy7Audio,
  sleepy8Audio,
  sleepy9Audio,
  sleepy10Audio,
  sleepy11Audio,
  sleepy12Audio,
  sleepy13Audio,
  sleepy14Audio,
  sleepy15Audio,
  sleepy16Audio,
  sleepy17Audio,
];

export default SLEEPY_LINKS;
