export const BACKGROUND_LINKS_LIST = [
	{
		set: 'chill',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/BDR%20Day%20112521%20%281%29.mp4',
	},
	{
		set: 'chill',
		scene: 'scene1',
		day: false,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/BDR%20STARRY%20NIGHT%20-.mp4',
	},
	{
		set: 'chill',
		scene: 'scene1',
		day: true,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/BDR%20RAINY%20DAY.mp4',
	},
	{
		set: 'chill',
		scene: 'scene1',
		day: false,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/BDR%20RAINY%20NIGHT.mp4',
	},
	{
		set: 'chill',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/LVR%20Day%20112521.mp4',
	},
	{
		set: 'chill',
		scene: 'scene2',
		day: false,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/LVR%20STARRY%20NIGHT.mp4',
	},
	{
		set: 'chill',
		scene: 'scene2',
		day: true,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/LVR%20RAINY%20DAY.mp4',
	},
	{
		set: 'chill',
		scene: 'scene2',
		day: false,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/chill-vibes/LVR%20RAINY%20NIGHT.mp4',
	},
	{
		set: 'northern',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cottage/Cottage+Int+Final.mp4',
	},
	{
		set: 'northern',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cottage/Cottage+Ext+Final.mp4',
	},
	{
		set: 'desk',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/study/city%20scene.mp4',
	},
	{
		set: 'desk',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/study/beach%20scene.mp4',
	},
	{
		set: 'desk',
		scene: 'scene3',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/study/snow%20scene%20wo%20snow.mp4',
	},
	{
		set: 'forest',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/forest/inside.mp4',
	},
	{
		set: 'forest',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/forest/outside.mp4',
	},
	{
		set: 'ocean',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/ocean/ocean-tales.mp4',
	},
	{
		set: 'ocean',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/ocean/ocean-tales-out.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/inside.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene1',
		day: false,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/inside-night.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene1',
		day: true,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/inside-rain.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene1',
		day: false,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/inside-night-rain.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/outside.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene2',
		day: false,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/outside-night.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene2',
		day: true,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/outside-rain.mp4',
	},
	{
		set: 'cafe',
		scene: 'scene2',
		day: false,
		rainy: true,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/cafe/outside-night-rain.mp4',
	},
	{
		set: 'van',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/van/van.mp4',
	},
	{
		set: 'van',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/van/van-out.mp4',
	},
	{
		set: 'summer',
		scene: 'scene1',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/summer/summer.mp4',
	},
	{
		set: 'summer',
		scene: 'scene2',
		day: true,
		rainy: false,
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/scenes/summer/summer-out.mp4',
	},
];

export const TUTORIAL_VIDEOS_LINKS = [
	{
		name: 'tutorial-1',
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/tutorial/Video%201%20-%20Mixer.mp4',
		title1: 'The Perfect Playlist',
		title2: 'With One Click',
		des1: 'Hit play and get into the zone instantly. No ads. No distracting lyrics.',
		des2: '3 Stations to suit your mood: chill, jazzy or sleepy.',
	},
	{
		name: 'tutorial-2',
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/tutorial/Video%202%20-%20Scenes.mp4',
		title1: 'Craft Your Focus Environment',
		des1: 'Would you rather get it done in the cafe, or escape to the beach? Lofi.co gives you both with interactive artworks.',
		des2: 'Basic users can access 2 artworks, while premium users have exclusive access to a growing library of 13+ illustrations.',
	},
	{
		name: 'tutorial-3',
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/tutorial/Video%204%20-%20Mixer%20Environment.mp4',
		title1: 'Cut Out Distractions',
		title2: 'With Peaceful Sounds',
		des1: 'Drown out even the noisiest neighbour with soothing background sounds. Each artwork comes with adjustable sounds like rain, waves or birds. Some sounds change the scene’s visuals.',
		des2: 'Basic users get 3 sound effects. Premium users can mix and match 12+ sounds.',
	},
	{
		name: 'tutorial-4',
		link: 'https://s3.us-east-2.amazonaws.com/lofi.co/lofi.co/tutorial/Video%203%20-%20Focus%20_%20History%20%281%29.mp4',
		title1: 'The Focus Zone (Premium)',
		des1: 'Deadline coming up? The Focus Zone lets you stay on track by gathering the best focus tools in one place - away from your distracting smartphone.',
		des2: `- Pomodoro timer: get more done in less time (without burning out)
- Notepad: never let a thought disappear
- Time logger: track your progress
- To-do list: always know what to do next`,
	},
];
